---
.travis.yml:
  secure: "tJxdfj1JCPSX61grU3tMGpRL5MRj38MoG0/NwlWC0N+lpchi6KV+DMdioqrPVwRtGixKlVYISS/2AeFVpZmrDtMzPKdkAOEoE2BT9LuRK7yC39ehzxOwwTNc9mfWBJhPOQsS7lGu7RJx3VfSxGCEI2TC9DvkkbJekhJmO5yAsFQ="
spec/spec_helper_acceptance.rb:
  unmanaged: false
